/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/maHead.glb -o src/components/Model.tsx -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ObjectMap } from "@react-three/fiber";

type GLTFResult = GLTF & ObjectMap & {
  nodes: {
    Node1: THREE.Mesh;
  };
  materials: {
    x1: THREE.MeshStandardMaterial;
  };
};

export function Model(props: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF("/models/maHead.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Node1.geometry}
        material={materials.x1}
        position={[-0.003, -0.001, 0.001]}
        rotation={[1.43, -0.205, 2.683]}
      />
    </group>
  );
}

useGLTF.preload("/models/maHead.glb");
